boombike/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from sitemaps import ViewSitemap

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'views_sitemap': ViewSitemap,
}

urlpatterns = patterns('',
#    url(r'^404$', 'info.views.page_not_found', name='page_not_found'),
    # Translation
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {
     'sitemaps': sitemaps,
     'template_name': 'info/custom_sitemap.html'},),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

     # Albums
     url(_(r'^albums$'), 'info.views.albums', name='albums'),

     # Facebook all auth
     (r'^accounts/', include('allauth.urls')),

)

urlpatterns += i18n_patterns('',
    url(_(r'^$'), 'info.views.home', name='home'),
    url(_(r'^bicycle-touring$'), 'info.views.bicycle_touring', name='bicycle-touring'),
    url(_(r'^boom-festival$'), 'info.views.boom_festival', name='boom-festival'),
    url(_(r'^boom-and-bike$'), 'info.views.boom_and_bike', name='boom-and-bike'),
    url(_(r'^get-there$'), 'info.views.get_there', name='get-there'),
    url(_(r'^together$'), 'info.views.together', name='together'),
    url(_(r'^get-there$'), 'info.views.get_there', name='get-there'),
    url(_(r'^city_visit/(?P<location>.+)$'), 'info.views.city_visit', name='city_visit'),
    url(_(r'^user_checkpoints/(?P<id>[0-9]+)$'), 'info.views.user_checkpoints', name='user_checkpoints'),
)

#urlpatterns += patterns('django.contrib.auth.views',
#    (_(r'^accounts/login/$'),  'login'),
#    (_(r'^accounts/logout/$'), 'logout'),
#)

handler404 = 'info.views.page_not_found'

info/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

FRANCE_COUNTRY_NAME = u'France'
SPAIN_COUNTRY_NAME = u'Spain'
PORTUGAL_COUNTRY_NAME = u'Portugal'

COUNTRY_CHOICES = (
    (FRANCE_COUNTRY_NAME, FRANCE_COUNTRY_NAME),
    (SPAIN_COUNTRY_NAME, SPAIN_COUNTRY_NAME),
    (PORTUGAL_COUNTRY_NAME, PORTUGAL_COUNTRY_NAME),
)


class City(models.Model):
    name = models.CharField(max_length=128)
    zip_code = models.CharField(max_length=8)
    country = models.CharField(max_length=64, choices=COUNTRY_CHOICES)

    def __unicode__(self):
        return '%s - %s - %s' % (self.name, self.zip_code, _(self.country))

    class Meta:
        verbose_name = u'City'
        ordering = ('name',)
        verbose_name_plural = u'Cities'
        unique_together = ('name', 'zip_code', 'country')


class CityVisit(models.Model):
    user = models.ForeignKey(User)
    location = models.CharField(max_length=256)
    date = models.DateField()

    class Meta:
        ordering = ('date',)
        verbose_name = _('Checkpoint')
        verbose_name_plural = _('Checkpoints')

info/forms.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

# Django imports
from django import forms
from django.utils.translation import ugettext as _

# Internal imports
from info.models import CityVisit
from boombike.settings import DATE_INPUT_FORMATS

class VisitedCityForm(forms.ModelForm):
    """
    A form to create a CityVisit with some autocomplete to select a city saved in DB.
    """
#    user = forms.CharField(widget=forms.HiddenInput, required=False)
    location = forms.CharField(widget=forms.TextInput(attrs={'disabled' : ''}),
                               label=_('Location'))
    date = forms.DateField(label=_('Visit date'),
                           widget=forms.TextInput(attrs={'class' : 'datepicker'}),
                           input_formats=DATE_INPUT_FORMATS)

    def save(self, commit=True, user=None):
        # There must be a user
        if user is None:
            return

        location = self.cleaned_data['location']
        date = self.cleaned_data['date']

        instance = CityVisit(location=location, date=date, user=user)

        if commit:
            instance.save()

        return instance

    class Meta:
        model = CityVisit
        exclude = ('user', )

info/views.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

# Python imports
import json

# Django imports
from info.models import CityVisit
from django.shortcuts import render, render_to_response
from django.utils.translation import ugettext as _
from django_tables2   import RequestConfig
from django.db.models import Count
from django.contrib.auth.models import User

# Internal imports
from info.forms import VisitedCityForm
from info.tables import CityVisitTable, GroupedCityVisitTable
from boombike.settings import GOOGLE_MAPS_API_KEY

def home(request, template='info/home.html'):
    return render(request, template, {})

def bicycle_touring(request, template='info/bicycle_touring.html'):
    return render(request, template, {})

def boom_festival(request, template='info/boom_festival.html'):
    return render(request, template, {})

def boom_and_bike(request, template='info/boom_and_bike.html'):
    return render(request, template, {})

def get_there(request, template='info/get_there.html'):
    return render(request, template, {})

def together(request, template='info/together.html'):
    context_dict = {}

    if request.method == 'GET':
        form = VisitedCityForm()
        context_dict['form'] = form

    elif request.method == 'POST':
        form = VisitedCityForm(request.POST)
        context_dict['form'] = form

        if form.is_valid(): # All validation rules pass
           city_visit = form.save(user=request.user) # Do not let the user change this by any mean :)
           message = u'%s "%s"' % (unicode(_("You successfully added a checkpoint at")), city_visit.location)
           context_dict['form'] = VisitedCityForm() # We want the form to blank here
        else:
            message = _('Something bad happened...')
            print form.errors

        context_dict['message'] = message

    if request.user.is_authenticated():
        user_city_visits = CityVisit.objects.filter(user=request.user)
        city_visits_table = CityVisitTable(user_city_visits, prefix='user')
        RequestConfig(request, paginate={"per_page": 10}).configure(city_visits_table)

        context_dict['nb_city_visits'] = user_city_visits.count()
        context_dict['city_visits_table'] = city_visits_table

    # Anyway, we get all the users city visits
    all_users_city_visits = CityVisit.objects.all().values('location').annotate(num_visits=Count('location'))
    all_users_city_visits_table = GroupedCityVisitTable(all_users_city_visits, prefix='all_users')
    RequestConfig(request, paginate={"per_page": 15}).configure(all_users_city_visits_table)
    context_dict['all_users_city_visits_table'] = all_users_city_visits_table
    context_dict['all_users_city_visits_count'] = len(all_users_city_visits)

    # Finally, we need the right API Key
    context_dict['GOOGLE_MAPS_API_KEY'] = GOOGLE_MAPS_API_KEY

    return render(request, template, context_dict)


def city_visit(request, location, template='info/city_visit.html'):
    context_dict = {}

    # Who are the users visiting the city?
    users_visiting = CityVisit.objects.filter(location=location)\
                        .order_by('user').values_list('user', flat=True).distinct()

    users = User.objects.filter(pk__in=users_visiting)
    context_dict['users'] = users
    context_dict['location'] = location

    return render(request, template, context_dict)


def user_checkpoints(request, id, template='info/user_checkpoints.html'):
    context_dict = {}

    # Get the user
    user = User.objects.get(pk=id)

    # Get the user's checkoints
    user_checkpoints = CityVisit.objects.filter(user=user)

    # Build the table
    user_checkpoints_table = CityVisitTable(user_checkpoints, prefix='user')
    RequestConfig(request, paginate={"per_page": 15}).configure(user_checkpoints_table)
    context_dict['user_checkpoints_table'] = user_checkpoints_table

    context_dict['username'] = user.username

    user_unique_checkpoints = user_checkpoints.order_by('location')\
        .values_list('location', flat=True).distinct()

    context_dict['user_unique_checkpoints'] = json.dumps(list(user_unique_checkpoints))
    context_dict['current_user'] = user

    context_dict['language_code'] = request.LANGUAGE_CODE

    return render(request, template, context_dict)


def page_not_found(request, template='404.html'):
    response = render(request, template)
    response.status_code = 404
    return response

def albums(request, template='music/albums.html'):
    return render_to_response(template)

templates/info/base.html
{% load staticfiles %}
{% load i18n %}
{% load info_extras %}

<!DOCTYPE html>
<html>
    <head>
        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <!--[if IE]>
            <link rel="stylesheet" href="{% static 'css/ie_specifics.css' %}">
        <![endif]-->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta name="author" content="Quentin CARON">

        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <link rel="stylesheet"
              media="(min-device-width : 768px) and (max-device-width : 1024px)"
              href="{% static 'css/tablet.css' %}">
        <link rel="stylesheet"
              media="(min-device-width : 320px) and (max-device-width : 480px)"
              href="{% static 'css/mobile.css' %}">

        <link rel="icon" type="image/png" href="{% static 'img/bicycle_16x16_favicon.png' %}">
        
        <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
        <script src="{% static 'js/mobile.js' %}"></script>
        <script src="{% static 'js/jquery.bpopup.min.js' %}"></script>
        <script src="{% static 'js/additional.js' %}"></script>

        <!-- Lightbox image effects -->
        <link href="{% static 'lightbox/css/lightbox.css' %}" rel="stylesheet" />
        <script src="{% static 'lightbox/js/lightbox-2.6.min.js' %}"></script>

        <script>
            var static_url = "{% static '' %}";
            
            $(function() {
                $('span.share').bind('click', function(e) {
                    e.preventDefault();
                    $('#share').bPopup();
                });
                
                $('a#popup_contact').bind('click', function(e) {
                    e.preventDefault();
                    $('#contact').bPopup();
                });
            });
        </script>

        <!-- GA tracking -->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-48361394-1', 'boom-bike.info');
          ga('send', 'pageview');

        </script>

        {% block head %}
        {% endblock %}
    </head>
    <body>
        <div id="fb-root"></div>
        <script>
            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>

        <script>
            $(function() {
                $("form#language_form select[name=language]").change(function() {
                    var next = $("form#language_form select[name=language]")
                        .find(":selected").data("next");

                    $("form#language_form input[name=next]").val(next);

                    $("form#language_form").submit();
                });
            });
        </script>

        <header id="header" data-scroll="yes">
            <h1>
                <a href="/">- Boom Bike -</a>
            </h1>

            <nav id="mobile_menu">
                <ul>
                    <li>
                        <img src="{% static 'img/menu.png' %}" id="img_menu">
                        <ul>
                            <li>
                                <a href="{% url 'bicycle-touring' %}">{% trans "Bicycle Touring" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'boom-festival' %}">{% trans "Boom Festival" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'boom-and-bike' %}">{% trans "Boom and Bike" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'get-there' %}">{% trans "Get there" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'together' %}">{% trans "Together" %}</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            
            <span class="share">
                <a href="#share">
                    <img src="{% static 'img/facebook.png' %}" alt="Accueil" class="img48 share">
                </a>
                <a href="#share">
                    <img src="{% static 'img/twitter.png' %}" alt="Accueil" class="img48 share">
                </a>
                <a href="#share">
                    <img src="{% static 'img/google_plus.png' %}" alt="Accueil" class="img48 share">
                </a>
            </span>
        </header>

        <div id="menu_container">
            <div id="menu" class="ribbon">
                <div class="left menu_item bicycle_touring_menu_item {% block nav_bicycle_touring %}{% endblock %}">
                    <a href="{% url 'bicycle-touring' %}">{% trans "Bicycle Touring" %}</a>
                </div>
                <div class="left menu_item boom_festival_menu_item {% block nav_boom_festival %}{% endblock %}">
                    <a href="{% url 'boom-festival' %}">{% trans "Boom Festival" %}</a>
                </div>
                <div class="left menu_item boom_and_bike_menu_item {% block nav_boom_and_bike %}{% endblock %}">
                    <a href="{% url 'boom-and-bike' %}">{% trans "Boom and Bike" %}</a>
                </div>
                <div class="left menu_item get_there_menu_item {% block nav_go_there %}{% endblock %}">
                    <a href="{% url 'get-there' %}">{% trans "Get there" %}</a>
                </div>
                <div class="left menu_item together_menu_item {% block nav_together %}{% endblock %}">
                    <a href="{% url 'together' %}">{% trans "Together" %}</a>
                </div>
                <div class="clear"></div>
            </div>
        </div>

        <div id="language_div">
            <form action="{% url 'set_language' %}" method="post" id="language_form">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">

                <select name="language">
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option 
                        value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}
                        data-next="{% change_lang language.code %}"
                        >
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
                </select>
            </form>
        </div>

        <div id="main_content">
            {% block content %}
            {% endblock %}
        </div>
    
        <footer id="footer" data-scroll="yes">
            <div id="sitemap">
                <div class="left sitemap_col">
                    <h4>Boom-bike</h4>
                    <hr class="footer_hr">
                    <a href="{% url 'home' %}">{% trans "Home" %}</a><br>
                    <a href="{% url 'bicycle-touring' %}">{% trans "Bicycle Touring" %}</a><br>
                    <a href="{% url 'boom-festival' %}">{% trans "Boom Festival" %}</a><br>
                    <a href="{% url 'boom-and-bike' %}">{% trans "Boom and Bike" %}</a><br>
                    <a href="{% url 'get-there' %}">{% trans "Get there" %}</a><br>
                    <a href="{% url 'together' %}">{% trans "Together" %}</a>
                </div>
                <div class="left sitemap_col">
                    <h4>{% trans "Follow us" %}</h4>
                    <hr class="footer_hr">
                    <a href="https://www.facebook.com/boombike.info" target="_blank">Facebook</a><br>
                    <a href="https://twitter.com/boom_bike_info" target="_blank">Twitter</a><br>
                    <a href="https://plus.google.com/110868265478762489436" target="_blank">Google +</a>
                </div>
                <div class="clear"></div>
            </div>
            <hr class="footer_hr section_sep">
            <div id="other">
                <a href="#contact" id="popup_contact">
                    <img src="{% static 'img/email.png' %}" alt="email" class="img64 contact">
                </a>
            </div>
        </footer>

        <div id="share" class="popup">
            <span class="button b-close">
                <span>X</span>
            </span>
            
            <div class="share_title">
                <h2>Share me all night long...</h2>
            </div>
            <div class="left share_column">
                <h3>Facebook</h3>
                <div class="fb-share-button"
                     data-href="http://boom-bike.info"
                     data-width="200"
                     data-type="box_count"></div>
            </div>

            <div class="left share_column">
                <h3>Twitter</h3>
                <a href="https://twitter.com/share" class="twitter-share-button"
                   data-url="http://boom-bike.info"
                   data-text="Cycle it to Boom" data-via="boom_bike_info"
                   data-lang="fr" data-size="large">Tweeter</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </div>

            <div class="left share_column">
                <h3>Google +</h3>
                <div class="g-plus" data-action="share" data-href="http://boom-bike.info"
                     data-annotation="vertical-bubble"></div>
            </div>

            <div class="clear"></div>
        </div>

        <div id="contact" class="popup">
            <span class="button b-close">
                <span>X</span>
            </span>

            <div class="contact_title">
                <h2>Contact</h2>
            </div>
            <p>{% trans "Have questions? Need information?" %}</p>
            <p>
                {% trans "Contact me at" %}
                <a href="mailto:contact@boom-bike.info" target="_top">
                    contact@boom-bike.info
                </a>
            </p>
        </div>

        <!-- Google + async -->
        <script type="text/javascript">
          window.___gcfg = {
              lang: 'fr'
          };

          (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
        </script>

    </body>
</html>

templates/info/city_visit.html
{% extends "info/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
<title>Boom Bike ~ {% trans "Visit" %} {{ location }}</title>
<meta name="description"
      content="{% trans 'city_meta_description' %}">

{% endblock %}

{% block nav_together %}active{% endblock %}

{% block content %}
<div id="city_visit_content" class="article_style">
    <div id="article_title">
        <h2 class="together">
            {% trans "Together" %}
        </h2>
    </div>

    <div id="article_content">
        <h3>
            {% trans "Bycycle tourers visiting" %} <strong>{{ location }}</strong>
        </h3>

        <p>
            {% if users %}
                <ul>
                {% for user in users %}
                    <li>
                        <a href="{% url 'user_checkpoints' id=user.pk %}">{{ user }}</a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                {% trans "Nobody is cycling to this location" %}
            {% endif %}
        </p>

    </div>
</div>
{% endblock %}

templates/info/together.html
{% extends "info/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load django_tables2 %}

{% block head %}
<title>Boom Bike ~ {% trans "together_title" %}</title>
<meta name="description"
      content="{% trans 'together_meta_description' %}">

<script src="{% static 'pickadate/picker.js' %}"></script>
<script src="{% static 'pickadate/picker.date.js' %}"></script>
<link rel="stylesheet" href="{% static 'pickadate/themes/default.css' %}">
<link rel="stylesheet" href="{% static 'pickadate/themes/default.date.css' %}">

<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />

<script src="{% static 'jquery-ui/js/jquery-ui-1.10.4.custom.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'jquery-ui/css/flick/jquery-ui-1.10.4.custom.min.css' %}">

<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&key={{ GOOGLE_MAPS_API_KEY }}&sensor=false&language=en">
</script>

<script>
/*
 * Google maps
 */

// Places autocomplete
function initialize() {
    var mapOptions = {
        center: new google.maps.LatLng(46.306884, 4.828731),
        zoom: 4,
        streetViewControl: false
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

    var input = /** @type {HTMLInputElement} */(
    document.getElementById('pac-input'));

    var types = document.getElementById('type-selector');
    map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
    map.controls[google.maps.ControlPosition.TOP_LEFT].push(types);

    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.bindTo('bounds', map);

    var infowindow = new google.maps.InfoWindow();
    var marker = new google.maps.Marker({
        map: map,
        anchorPoint: new google.maps.Point(0, -29)
    });

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
        infowindow.close();
        marker.setVisible(false);
        var place = autocomplete.getPlace();
        if (!place.geometry) {
            return;
        }

        // If the place has a geometry, then present it on a map.
        if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
        } else {
            map.setCenter(place.geometry.location);
            map.setZoom(15);  // Why 15? Because it looks good.
        }
        marker.setIcon(/** @type {google.maps.Icon} */({
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(35, 35)
        }));
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);

        var address = '';
        if (place.address_components) {
            address = [
                (place.address_components[0] && place.address_components[0].short_name || ''),
                (place.address_components[1] && place.address_components[1].short_name || ''),
                (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
        }

        infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
        infowindow.open(map, marker);

        // Activate the get_google_maps_search button
        $("button#get_google_maps_search").removeAttr("disabled");
    });

    // Sets a listener on a radio button to change the filter type on Places
    // Autocomplete.
    function setupClickListener(id, types) {
        var radioButton = document.getElementById(id);
        google.maps.event.addDomListener(radioButton, 'click', function() {
            autocomplete.setTypes(types);
        });
    }

    setupClickListener('changetype-all', []);
    setupClickListener('changetype-establishment', ['establishment']);
    setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

function pac_input_changed(value) {
    if (value == null || value == "") {
        $("button#get_google_maps_search").attr("disabled", "")
    }
}

$(document).ready(function() {
    $('.datepicker').pickadate({
        formatSubmit: 'yyyy/mm/dd',
        hiddenName: true,
        onSet: function(context) {
            if($("#id_location").val() != "" &&
               $("#id_location").val() != null &&
               $("input#id_date").val() != "" &&
               $("input#id_date").val() != null) {
                $("input#submit_form").removeAttr("disabled")
            }
        }
    });

    $("button#get_google_maps_search").click(function() {
        $("#id_location").val(document.getElementById("pac-input").value);
    });

    $("#city_visit_form").submit(function() {
        $("#id_location").removeAttr("disabled");
    });

    if ("{{ message }}" != "") {
        $('#message').bPopup();
    }

});

</script>

{% endblock %}

{% block nav_together %}active{% endblock %}

{% block content %}
<div id="together_content" class="article_style">
    <div id="article_title">
        <h2 class="together">
            {% trans "Together" %}
        </h2>
    </div>

    <div id="article_content">
        <h3>
            {% trans "Visited cities" %}
        </h3>

        <div class="checkpoints_overview">
            {% if user.is_authenticated %}
                <div class="left half">
                    <h4>
                        {% trans "Hello" %} {{ user.username }} !
                    </h4>
                    {% if city_visits_table.data.queryset %}
                        <p>
                            {% trans "You defined" %} {{ nb_city_visits }} {% trans "checkpoint(s)" %}:
                        </p>

                        <div class="parent_table_container">
                            {% render_table city_visits_table %}
                        </div>
                    {% else %}
                        <p>
                            {% trans 'You have no checkpoint yet.' %}
                        </p>
                    {% endif %}
                </div>
            {% endif %}

            <div class="left {% if user.is_authenticated %}half{% else %}full{% endif %}">
                <h4>
                    {% trans "Boom Bikers checkpoints" %}
                </h4>
                {% if all_users_city_visits_table.data.queryset %}
                    <p>
                        {{ all_users_city_visits_count }} {% trans 'cities will be visited by bikers' %}:
                    </p>
                    <div class="parent_table_container">
                        {% render_table all_users_city_visits_table %}
                    </div>
                {% else %}
                    <p>
                        {% trans 'No checkpoint defined yet.' %}
                    </p>
                {% endif %}
            </div>
            <div class="clear"></div>
        </div>

        {% if not user.is_authenticated %}
        <h3>
            {% trans "Login / create an account" %}
        </h3>
        <p>
            {% trans "You are not logged in." %}
        </p>
        <p>
            {% trans 'Would you like to create an account? We implemented a Facebook login to make it simple but a Facebook account is not mandatory. Click "I want to login" to use Facebook.' %}<br>
            {% trans "Once logged in, you will be able to define checkpoints and other cyclists will be able to contact you by email." %}
        </p>
        <p>
            {% trans "Anyway, we will only ask for your name and email address, we do not save any personal data." %}
        </p>
        <p>
            <a href="/accounts/login">
                {% trans "> I want to login <" %}
            </a>
        </p>
        <p>
            <a href="/accounts/signup">
                {% trans "> I want to create an account <" %}
            </a>
        </p>

        {% endif %}

        {% if user.is_authenticated %}

            <!-- Show a foldable city visit form -->
            <h3>
                {% trans "Add a city you plan to visit" %}
            </h3>

            <input id="pac-input"
                   placeholder="{% trans 'Enter a location' %}"
                   onkeyup="pac_input_changed(this.value)"/>

            <div id="map-canvas"></div>

            <form action=""
                  method="POST"
                  id="city_visit_form">

                {% csrf_token %}

                <div>
                    <button type="button"
                            class="button"
                            id="get_google_maps_search"
                            disabled>
                        {% trans 'Use my Google Maps search as location' %}
                    </button>
                </div>
                <div>
                    <label for="{{ form.location.auto_id }}">
                        {{ form.location.label }}
                    </label>
                    {{ form.location }}
                </div>
                <div>
                    <label for="{{ form.date.auto_id }}">
                        {{ form.date.label }}
                    </label>
                    {{ form.date }}
                </div>

                <input type="submit" 
                       class="button validate"
                       value="{% trans 'Add this checkpoint' %}"
                       id="submit_form"
                       disabled />

            </form>

            <h3>
                {% trans "Logout" %}
            </h3>
            <p>
                <a href="/accounts/logout">
                    {% trans "> I want to logout <" %}
                </a>
            </p>
        {% endif %}

        <!--
            The user has added a city or an error message is to be displayed
        -->
        <div id="message" class="popup">
            <span class="button b-close">
                <span>X</span>
            </span>

            <div class="message_title">
                <h2>Checkpoint</h2>
            </div>
            <p>{{ message }}</p>
        </div>

    </div>
</div>
{% endblock %}